# Dataset configuration
sdf_points: 10000
sdf_sample_type: 'uniform'
sdf_res: 256
s3_bucket: 'build3d-wavelets'
s3_prefix: 'dataset'
use_s3: true
resolution: 256
max_depth: 3
max_training_level: 2
point_num: 16384
keep_level: 2
data_keep_level: 2
wavelet: 'bior6.8'
padding_mode: 'constant'
use_normalization: true
use_shift_mean: false
start_stage: 0
use_adaptive_stage_update: false
no_rebalance_loss: false
use_compact_indices: true
sample_threshold_ratio: 0.0625
use_batched_threshold: true
over_write: false
dataset_path: 'ShapeNet_V2'
max_images_num: 40
num_pc_points: 2048
input_view_cnt: 1
clip_model_type: 'L-14'
wavelet_transform: null
use_local_storage: false
train_mode: 'None'
batch_size: 3
lr: 1e-5